name: Cookbook CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dpendencies
        run: npm install
      - name: Starting the app as backgound process
        run: npm run start &
      - name: "Start unit test"
        run: npm run test:unit
      - name: "Show my SoftUni username"
        run: echo "panastasovsoftuni"

  ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-test

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dpendencies
        run: npm install
      - name: Install playwright library for UI tests
        run: npx playwright install
      - name: Starting the app as backgound process
        run: npm run start &
      - name: Execute the UI tests
        run: npm run test:ui

  deploy-to-rendercom:
    runs-on: ubuntu-latest
    needs: ui-tests

    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
